//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBGOODS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        public string username { get; set; }
        public string FULLNAME { get; set; }
        public string password { get; set; }
        public string Phone { get; set; }
    }
}
