//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WEBGOODS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_billimport
    {
        public int billid { get; set; }
        public int productid { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual bill_import bill_import { get; set; }
        public virtual product product { get; set; }
    }
}
