'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class bill_import
    Public Property id As Integer
    Public Property datecreate As Nullable(Of Date)
    Public Property companyname As String
    Public Property totalprice As Nullable(Of Integer)

    Public Overridable Property product_billimport As ICollection(Of product_billimport) = New HashSet(Of product_billimport)

End Class
