'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class cart
    Public Property id As Integer
    Public Property productid As Nullable(Of Integer)
    Public Property customerid As Nullable(Of Integer)
    Public Property quantity As Nullable(Of Integer)

    Public Overridable Property customer As customer
    Public Overridable Property product As product

End Class
