'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class customer
    Public Property id As Integer
    Public Property fullname As String
    Public Property phonenumber As String
    Public Property password As String

    Public Overridable Property carts As ICollection(Of cart) = New HashSet(Of cart)
    Public Overridable Property customerbills As ICollection(Of customerbill) = New HashSet(Of customerbill)

End Class
