'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class DBSEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=DBSEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property accounts() As DbSet(Of account)
    Public Overridable Property bill_import() As DbSet(Of bill_import)
    Public Overridable Property carts() As DbSet(Of cart)
    Public Overridable Property categories() As DbSet(Of category)
    Public Overridable Property customers() As DbSet(Of customer)
    Public Overridable Property customerbills() As DbSet(Of customerbill)
    Public Overridable Property products() As DbSet(Of product)
    Public Overridable Property product_billimport() As DbSet(Of product_billimport)

End Class
