'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product
    Public Property id As Integer
    Public Property name As String
    Public Property description As String
    Public Property price As Nullable(Of Integer)
    Public Property categoryid As Nullable(Of Integer)
    Public Property quantity As Nullable(Of Integer)
    Public Property img As String

    Public Overridable Property carts As ICollection(Of cart) = New HashSet(Of cart)
    Public Overridable Property category As category
    Public Overridable Property customerbills As ICollection(Of customerbill) = New HashSet(Of customerbill)
    Public Overridable Property product_billimport As ICollection(Of product_billimport) = New HashSet(Of product_billimport)

End Class
