'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product_billimport
    Public Property billid As Integer
    Public Property productid As Integer
    Public Property quantity As Nullable(Of Integer)

    Public Overridable Property bill_import As bill_import
    Public Overridable Property product As product

End Class
